### ISSUE TITLE
Fatal error: Class 'Mandrill' not found in /home/myshulca/public_html/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line

### ISSUE THREAD

**Issue by manojind** [ebizmarts/magento2-abandonedcart#11]
Fatal error: Class 'Mandrill' not found in /home/myshulca/public_html/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line

**Comment by ebizmarts-keller** [comment]
You have to install the Mandrill library to get rid of this error.

https://packagist.org/packages/mandrill/mandrill

**Comment by manojind** [comment]
How i can install   https://packagist.org/packages/mandrill/mandrill  ???? In magneto 2

**Comment by manojind** [comment]
How i can install https://packagist.org/packages/mandrill/mandrill in magneto 2 ?????

**Comment by manojind** [comment]
I run git clone https://bitbucket.org/mailchimp/mandrill-api-php.git/wiki This comand in 
Bin folder ???
let me know how and where i need to installe that

**Comment by gonzaloebiz** [comment]
Read the magento2 manual to know how to install a package via composer

Best
