### ISSUE TITLE
mails not shoot for loggedIn user

### ISSUE THREAD

**Issue by balwant20** [ebizmarts/magento2-abandonedcart#16]
when logged in user make cart session.abandonment mails are not shoot to the customer.but after login customer subscribe any section of the website then it works fine.
how????
can plz plz figure out what is problem behind this?

thanks in advance......!!!!!
waiting for your quick response

**Comment by gonzaloebiz** [comment]
this extension is deprecated and not supported any more.
Please use https://github.com/mailchimp/mc-magento2

Best
