### ISSUE TITLE
Install while installing Magento gives error

### ISSUE THREAD

**Issue by stefandoorn** [ebizmarts/magento2-abandonedcart#4]
_Accidentally filed it here (https://github.com/ebizmarts/magento2-magemonkey/issues/9) already, but here again as it applies to this repository actually._

I don't have the logs unfortunately, but basically what happened today:
- In app/etc/config.php the MageMonkey module was enabled
- We ran a full Magento CLI install
- At step 10 or something, the MageMonkey installer kicks in, trying to adjust the quote table, which doesn't exist.

This leads me to think that the dependencies of the MageMonkey module should be refined. In /etc/module.xml you can define which modules need to be present, before this module can be installed/updated, etc. In there I don't see any dependencies. Basically it comes down to this part of the manual that I think is necessary: http://devdocs.magento.com/guides/v2.0/architecture/archi_perspectives/components/modules/mod_depend.html

**Comment by stefandoorn** [comment]
Thanks! When will this be in a new release?

**Comment by gonzaloebiz** [comment]
We have no ETA for a new release

**Comment by stefandoorn** [comment]
Ok. Problem is that now you can't install a new development environment with this module included, as it breaks the installer order. So basically the package is broken..

**Comment by SantiParagarino** [comment]
Hello,

New version have been released. https://github.com/ebizmarts/magento2-abandonedcart/releases/tag/3.0.2
Thanks again for helping us with your contribution.
Enjoy!
