### ISSUE TITLE
Plugin aroundSave always set Abandonedcart to Inactive

### ISSUE THREAD

**Issue by phupt** [ebizmarts/magento2-abandonedcart#9]
Line of code: !$this->_objectManager->create('\Ebizmarts\Mandrill\Helper\Data')->isActive($config->getStore()) always return true;

public function aroundSave(\Magento\Config\Model\config $config,\Closure $proceed)
{

    $ret = $proceed();
    
    $sectionId = $config->getSection();
    if($sectionId=='abandonedcart'&&!$this->_objectManager->create('\Ebizmarts\Mandrill\Helper\Data')->isActive($config->getStore()))
    {

        $this->_writer->save(\Ebizmarts\AbandonedCart\Model\Config::ACTIVE,0,$config->getScope(),$config->getScopeId());
    }
    
    return $ret;
    
}

**Comment by SantiParagarino** [comment]
Hello,

Thanks for your feedback.
That should only turn the module to inactive when Mandrill module is not enabled. Abandoned Cart module depends on Mandrill to work.

Regards.

**Comment by phupt** [comment]
Yes, I understand abd turn on both but it seems to be code logic when check 1 and 0 with true and false so it always return true
